language: node_js
node_js:
  - iojs
  - '0.12'
sudo: false
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
script:
  - gulp ci
deploy:
  provider: npm
  email: egy186@yahoo.co.jp
  api_key:
    secure: KKqoz7TDoO2mIVmcV/puyrMHZCTCDbXrsj0Tkled8l+BCp7DthbwPtiohXfnARSIpt7/XxAPoMvSqMD5qB2qlGCRxs9oFeta3kiakhr/ynCZi3f2kccN/pv/RKrkFVgVVixr59lgzDC7VuZDY+nti548nMeY3zkebcfjz9ZbzUA=
  on:
    tags: true
    repo: egy186/icojs
